
services:
  postgres:
    image: postgres:15-alpine
    container_name: referral_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: referral_db
    ports:
      - "5432:5432"
    auto_restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  flask-app:
    image: meyanksingh/flask-server:latest
    container_name: flask-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/referral_db
      - SECRET_KEY=test
      - JWT_SECRET_KEY=test
      - FRONTEND_URL=http://localhost:3000,http://localhost:5173
    auto_restart: always
    depends_on:
      - postgres
  
  


volumes:
  pgdata:

